### PR TITLE
fix(swagger-ui): support `persistAuthorization` and boolean option

### LINKED ISSUE #264: swagger-ui: support `persistAuthorization`
[`persistAuthorization`](https://github.com/swagger-api/swagger-ui/blob/d3bb64f1de150ea1ff677accf705c9ce0ae9fe85/flavors/swagger-ui-react/README.md?plain=1#L161) allows credentials to be stored in localstorage. this is useful for quickly refreshing and testing changes in API with swagger UI.

```ts
new Hono()
	.get("/openapi.json", (c) => c.json(doc))
	.get("/openapi", swaggerUI({ url: "/openapi.json", persistAuthorization: true }))
```
however, this doesn't type checks and will not render properly,

```ts
new Hono()
	.get("/openapi.json", (c) => c.json(doc))
	.get("/openapi", swaggerUI({
          url: "/openapi.json",
          manuallySwaggerUIHtml: (asset) => /*html*/`
          <div>
              <div id="swagger-ui"></div>
              ${asset.css.map((url) => `<link rel="stylesheet" href="${url}" />`)}
              ${asset.js.map((url) => `<script src="${url}" crossorigin="anonymous"></script>`)}
              <script>
                  window.onload = () => {
                      window.ui = SwaggerUIBundle({
                          dom_id: '#swagger-ui',
                          url: '/openapi.json',
                          persistAuthorization: true,
                      })
                  }
              </script>
          </div>
          `
    }))
```
while this works.

I'm interested in opening PR.

### PR DESCRIPTION
**Pull request by scarf005**
- fix #264

### CODE REVIEW

**Comment by sor4chi** [comment]
Hi @scarf005, Thanks for PR! Nice work.
I’m creator of @hono/swagger-ui.
I didn’t notice such a option field existed.

BTW, I found that more unsupported fields from [this](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/).
Should we support all of these?

cc: @yusukebe

File: packages/swagger-ui/src/swagger/renderer.ts [hunk 1]
```diff
@@ -37,6 +39,7 @@ const RENDER_TYPE_MAP = {
   operationsSorter: RENDER_TYPE.RAW,
   requestInterceptor: RENDER_TYPE.RAW,
   responseInterceptor: RENDER_TYPE.RAW,
+  persistAuthorization: RENDER_TYPE.BOOLEAN,
```
Comment (sor4chi) [inline packages/swagger-ui/src/swagger/renderer.ts:42]: I don't think it is necessary to add `RENDER_TYPE.BOOELAN` because you can just use `RENDER_TYPE.RAW` for boolean.

File: .changeset/tiny-sheep-raise.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@hono/swagger-ui': patch
```
Comment (sor4chi) [inline .changeset/tiny-sheep-raise.md:2]: I think this changes will be minor release. How about this, @yusukebe?

**Review by sor4chi — COMMENTED** [review]
I've left some comments!

File: packages/swagger-ui/src/swagger/renderer.ts (hunk 1 above)
Comment (scarf005) [reply packages/swagger-ui/src/swagger/renderer.ts]: yeah that'd be better.

**Comment by yusukebe** [comment]
Hi @scarf005 

Looks good to me!

@sor4chi 

> BTW, I found that more unsupported fields from [this](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/).
> Should we support all of these?

As you like. But I'll merge this first.

**Comment by sor4chi** [comment]
@yusukebe OK, I'll create the issue!
