### PR TITLE
fix(auth-js): use HonoRequest.blob() instead of HonoRequest.raw.body()

### LINKED ISSUE #1169: [@hono/auth-js] After passing through validator/zValidator, receives: TypeError: This ReadableStream is disturbed (has already been read from), and cannot be used as a body.
### Which middleware has the bug?

@hono/auth-js

### What version of the middleware?

1.0.15

### What version of Hono are you using?

4.7.9

### What runtime/platform is your app running on? (with version if possible)

Cloudflare Workers

### What steps can reproduce the bug?

```ts
describe('reqWithEnvUrl()', async () => {
  const mockAdapter: Adapter = {
    createVerificationToken: vi.fn(),
    useVerificationToken: vi.fn(),
    getUserByEmail: vi.fn(),
    createUser: vi.fn(),
    getUser: vi.fn(),
    getUserByAccount: vi.fn(),
    updateUser: vi.fn(),
    linkAccount: vi.fn(),
    createSession: vi.fn(),
    getSessionAndUser: vi.fn(),
    updateSession: vi.fn(),
    deleteSession: vi.fn(),
  }

  globalThis.process.env = {
    AUTH_SECRET: 'secret',
  }

  const user = { email: 'hono@hono.hono', name: 'Hono' }

  const credentials = Credentials({
    credentials: {
      password: {},
    },
    authorize: (credentials) => {
      if (credentials.password === 'password') {
        return user
      }
      return null
    },
  })

  function getAuthConfig(): AuthConfig {
    return {
      secret: 'secret',
      providers: [credentials],
      adapter: mockAdapter,
      basePath: '/api/auth',
      callbacks: {
        jwt: ({ token, user }) => {
          if (user) {
            token.id = user.id
          }
          return token
        },
      },
      session: {
        strategy: 'jwt',
      },
    }
  }

  let cookie = ['']

  it('Should be able to instantiate new Request after passing through validator', async () => {
    const app = new Hono()

    app.use('*', initAuthConfig(getAuthConfig))
    app.use(
      '/api/auth/*',
      validator('form', (value, _) => {
        const csrfToken = value['csrfToken']
        return {
          csrfToken,
        }
      }),
      authHandler()
    )

    let csrfRes = await app.request('http://localhost/api/auth/csrf', {
      method: 'GET',
    })
    let { csrfToken } = await csrfRes.json()

    cookie = csrfRes.headers.getSetCookie()

    let headers = new Headers()
    headers.append('cookie', cookie[0])

    const signInRes = await app.request('http://localhost/api/auth/callback/credentials', {
      method: 'POST',
      headers,
      body: new URLSearchParams({
        csrfToken,
        password: 'password',
      }),
    })
    expect(signInRes.status).toBe(302)
    expect(signInRes.headers.get('location')).toBe('http://localhost')

    cookie = signInRes.headers.getSetCookie()

    const sessionCookie = cookie[1]

    headers = new Headers()
    headers.append('cookie', cookie[1])
    headers.append('Content-Type', 'application/json')

    csrfRes = await app.request('http://localhost/api/auth/csrf', {
      method: 'GET',
    });

    ({ csrfToken } = await csrfRes.json())

    cookie = csrfRes.headers.getSetCookie()

    headers = new Headers()
    headers.append('cookie', cookie[0])
    headers.append('cookie', sessionCookie)

    const req = new Request('http://localhost/api/auth/signout', {
      method: 'POST',
      body: new URLSearchParams({
        csrfToken,
        password: 'password',
      }),
      headers,
    })
    const res = await app.request(req)
    expect(res.status).toBe(302)
  })
})

```

### What is the expected behavior?

It should be able to instantiate new Request to be passed to Auth().

### What do you see instead?

```sh
TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:5574:17)
    at new Request (node:internal/deps/undici/undici:9801:48)
    at reqWithEnvUrl (/home/hambergerpls/repo/honojs/middleware/packages/auth-js/src/index.ts:52:18)
    at /home/hambergerpls/repo/honojs/middleware/packages/auth-js/src/index.ts:138:28
    at dispatch (file:///home/hambergerpls/repo/honojs/middleware/node_modules/hono/dist/compose.js:22:23)
    at file:///home/hambergerpls/repo/honojs/middleware/node_modules/hono/dist/compose.js:22:46
    at file:///home/hambergerpls/repo/honojs/middleware/node_modules/hono/dist/validator/validator.js:81:11
    at dispatch (file:///home/hambergerpls/repo/honojs/middleware/node_modules/hono/dist/compose.js:22:17)
    at /home/hambergerpls/repo/honojs/middleware/packages/auth-js/src/index.ts:123:5
    at dispatch (file:///home/hambergerpls/repo/honojs/middleware/node_modules/hono/dist/compose.js:22:17)

```

### Additional information

reqWithEnvUrl() failed to instantiate a new request from HonoRequest.raw due to HonoRequest.raw.body() consumed/disturbed after passing through Hono validator().

### PR DESCRIPTION
**Pull request by hambergerpls**
### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn changeset` at the top of this repo and push the changeset
- [x] Follow [the contribution guide](https://github.com/honojs/middleware?tab=readme-ov-file#how-to-contribute)

Fixes #1169

### CODE REVIEW

File: packages/auth-js/src/index.ts [hunk 1]
```diff
@@ -135,7 +135,27 @@ export function authHandler(): MiddlewareHandler {
       throw new HTTPException(500, { message: 'Missing AUTH_SECRET' })
     }
 
-    const res = await Auth(reqWithEnvUrl(c.req.raw, ctxEnv.AUTH_URL), config)
+    const body = await c.req.text()
```
Comment (yusukebe) [inline packages/auth-js/src/index.ts:138]: I think the following is better:

* Check the body before extracting it.
* Use `blob()` can support any body format instead of `text()`.

```diff
diff --git a/packages/auth-js/src/index.ts b/packages/auth-js/src/index.ts
index 2b3a0f0..0944203 100644
--- a/packages/auth-js/src/index.ts
+++ b/packages/auth-js/src/index.ts
@@ -135,11 +135,11 @@ export function authHandler(): MiddlewareHandler {
       throw new HTTPException(500, { message: 'Missing AUTH_SECRET' })
     }

-    const body = await c.req.text()
+    const body = c.req.raw.body ? await c.req.blob() : undefined
     const res = await Auth(
       reqWithEnvUrl(
         new Request(c.req.raw.url, {
-          body: body ? body : undefined,
+          body,
           cache: c.req.raw.cache,
           credentials: c.req.raw.credentials,
           headers: c.req.raw.headers,
```

File: .changeset/great-toys-knock.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@hono/auth-js': minor
```
Comment (yusukebe) [inline .changeset/great-toys-knock.md:2]: This should be `patch` instead of `minor`.

File: packages/auth-js/src/index.ts (hunk 1 above)
Comment (hambergerpls) [reply packages/auth-js/src/index.ts]: Thanks for the suggestion! I tried to use c.req.blob() and the tests were failed last time. Didn't realise that we have to check c.req.raw.body.

**Comment by hambergerpls** [comment]
@yusukebe I have made the changes, please review

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Hi @hambergerpls 

I've fixed the lint and formatting errors. Looks good. I'll merge and release a new version.
